### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by zwgmy** [Sagit-chu/openwrt-ci#7]
Configuring ppp-mod-pppoe.
 * check_conflicts_for: The following packages conflict with sagernet-core:
 * check_conflicts_for: 	v2ray-core * check_conflicts_for: 	xray-core * 
 * opkg_install_cmd: Cannot install package luci-app-ssr-plus.
 * check_conflicts_for: The following packages conflict with sagernet-core:
 * check_conflicts_for: 	v2ray-core * check_conflicts_for: 	xray-core * 
 * opkg_install_cmd: Cannot install package sagernet-core.
make[2]: *** [package/Makefile:70: package/install] Error 255
make[1]: *** [package/Makefile:111: /workdir/openwrt/staging_dir/target-x86_64_musl/stamp/.package_install] Error 2
make[2]: Leaving directory '/workdir/openwrt'
make[1]: Leaving directory '/workdir/openwrt'
make: *** [/workdir/openwrt/include/toplevel.mk:230: world] Error 2
Error: Process completed with exit code 2.

编译出错，源码没改动

**Comment by Sagit-chu** [comment]
已经修复
